spring.application.name=uberApp

#Below is config required to connect to PostgresSQL DB
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#SecurityConfig -> creating the secretKey for JWT.
#It needs to be a long Key(lengthwise not datatype) because the algorithm which we are using need 256bits key so 256bits means 32 bytes.
#This could be collection of random alphabets of size 32 bits or even greater than that , because bigger the length, less would be chances of
#guessing the secretKey.
jwt.secretKey=anjdnjadksjanfdkjks556fnsabfdanflwqdkq78qtewuk76dfsmknjnscsdjns23dwjnjd

#When change "ddl-auto=update" from "create-drop" then comment below as well , as we were taking the data from data.sql file to store in DB.
#When we have to use data.sql file to insert Data into DB then we have to specify below configuration
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#Below tells the file path from where data to fetch
spring.sql.init.data-locations=classpath:data.sql


#SMTP(Simple Mail Transfer Protocol) Config.

#Inside password either we can pass "GmailAccount Password" inside password field but that is not recommended because everyone can have access to
#your Gmail password OR we can pass "app Password" , steps to create app-password, S1-> Login Into GmailAccount, S2-> Go to manage your GoogleAccount,
#S3-> Go to security , make sure 2-Step verification is on , then search for App password you'll find it inside security then you'll get your app password.
#A Google App Password is a special 16-character password generated by Google that allows an application to access your Google account without using
#your actual Gmail password.

#username & password are for SMTP servers so that they can Authenticate that it's really you who is sending the Email & not someone else Sending the
#email on your behalf.These credentials will be authenticated at the authenticator Server at SMTP.

spring.mail.username = anmolmishra287@gmail.com
spring.mail.password = wswf hdgq iqne kbfx 
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
#The below two mentioned are used for security purposes
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true