spring.application.name=uberApp

#Below is config required to connect to PostgreSQL DB
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true


#When we have to use data.sql file to insert Data into DB then we have to specify below configuration
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#Below tells the file path from where data to fetch
spring.sql.init.data-locations=classpath:data.sql
